tap "andreybleme/lazycontainer", "https://github.com/andreybleme/lazycontainer"
tap "felixkratz/formulae"
tap "finnvoor/tools"
tap "nikitabobko/tap"
tap "oven-sh/bun"
tap "withgraphite/tap"
brew "act" # github actions debugger
brew "python3"
brew "autossh"
brew "awscli"
brew "cloudflared"
brew "cmake"
brew "container", link: false
brew "coreutils"
brew "bat" # cat with syntax highlighting (used by zsh-bat plugin)
brew "eza" # modern ls
brew "zoxide" # smarter cd (replaces the z plugin)
brew "atuin" # searchable, syncable shell history
brew "mise" # polyglot runtime version manager (replaces fnm/nvm/pyenv)
brew "git-delta" # syntax-highlighting git pager
brew "exiftool"
brew "ffmpeg"
brew "zstd"
brew "node"
brew "gawk"
brew "gh"
brew "go"
brew "hexedit"
brew "htop"
brew "pam-reattach"
brew "pipx"
brew "protobuf-c"
brew "pygments"
brew "qpdf"
brew "qrencode"
brew "rust"
brew "tmux"
brew "uv"
brew "viddy"
brew "walk"
brew "felixkratz/formulae/borders"
brew "oven-sh/bun/bun"
brew "withgraphite/tap/graphite"
cask "calibre"
cask "chatgpt"
cask "claude"
cask "claude-code"
#cask "container"
cask "discord"
cask "ghostty"
#cask "github"
cask "imageoptim"
#cask "istat-menus"
#cask "iterm2"
cask "logseq-og"
cask "raycast"
cask "sloth"
cask "stats"
#cask "tuple"
cask "vlc"
